name: ğŸš€ Release Package

on:
  push:
    branches: [main, beta]

jobs:
  release:
    name: ğŸ—ï¸ Release
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”‚ Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: ğŸ“š Install dependencies
        run: npm ci --force
      - name: ğŸ·ï¸ Install semantic-release extra plugins
        run: npm install --save-dev @semantic-release/changelog @semantic-release/git
      - name: ğŸ—ï¸ Build
        run: npm run build
      - name: ğŸš€ Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
